[build]
  command = "npm ci && npm run build"
  publish = "build"

[build.environment]
  CI = "false"
  GENERATE_SOURCEMAP = "false"
  NODE_VERSION = "18.20.3"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_VERSION = "18.20.3"
  CI = "false"

[context.deploy-preview.environment]
  NODE_VERSION = "18.20.3"
  CI = "false"

[context.branch-deploy.environment]
  NODE_VERSION = "18.20.3"
  CI = "false"
