[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "build"
  ignore = "server/"

[build.environment]
  CI = "false"
  GENERATE_SOURCEMAP = "false"
  NODE_VERSION = "18.20.3"
  NPM_VERSION = "9.6.7"
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_AUDIT = "false"
  NPM_CONFIG_UPDATE_NOTIFIER = "false"
  SKIP_PREFLIGHT_CHECK = "true"
  DISABLE_ESLINT_PLUGIN = "true"
  ESLINT_NO_DEV_ERRORS = "true"
  TSC_COMPILE_ON_ERROR = "true"
  NPM_CONFIG_CACHE = "/tmp/.npm"
  REACT_APP_GA4_MEASUREMENT_ID = "G-BDZZKFKYDV"
  REACT_APP_ENABLE_ANALYTICS = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_VERSION = "18.20.3"
  NPM_VERSION = "9.6.7"
  CI = "false"
  REACT_APP_GA4_MEASUREMENT_ID = "G-BDZZKFKYDV"
