[build]
  command = "npm install --legacy-peer-deps --force && npm run build"
  publish = "build"

[build.environment]
  CI = "false"
  NODE_VERSION = "18.20.3"
  SKIP_PREFLIGHT_CHECK = "true"
  GENERATE_SOURCEMAP = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
