[build]
  command = "npm ci --legacy-peer-deps --no-optional && npm run build"
  publish = "build"
  ignore = "server/"
  functions = "netlify/functions"

[build.environment]
  CI = "false"
  GENERATE_SOURCEMAP = "false"
  NODE_VERSION = "18.20.3"
  NPM_VERSION = "9.6.7"
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_AUDIT = "false"
  NPM_CONFIG_UPDATE_NOTIFIER = "false"
  SKIP_PREFLIGHT_CHECK = "true"
  DISABLE_ESLINT_PLUGIN = "true"
  ESLINT_NO_DEV_ERRORS = "true"
  TSC_COMPILE_ON_ERROR = "true"
  NPM_CONFIG_CACHE = "/tmp/.npm"
  REACT_APP_GA4_MEASUREMENT_ID = "G-BDZZKFKYDV"
  REACT_APP_ENABLE_ANALYTICS = "true"

# API Redirects to Netlify Functions (MUST come before catch-all)
[[redirects]]
  from = "/api/claude-chat"
  to = "/.netlify/functions/claude-chat"
  status = 200

[[redirects]]
  from = "/api/openai-chat"
  to = "/.netlify/functions/openai-chat"
  status = 200

[[redirects]]
  from = "/api/keyword-intelligence"
  to = "/.netlify/functions/keyword-intelligence"
  status = 200

[[redirects]]
  from = "/api/generate-content"
  to = "/.netlify/functions/generate-content"
  status = 200

[[redirects]]
  from = "/api/analyze-url"
  to = "/.netlify/functions/analyze-url"
  status = 200

# SPA Redirect for React Router (MUST come last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Performance headers
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[context.production.environment]
  NODE_VERSION = "18.20.3"
  NPM_VERSION = "9.6.7"
  CI = "false"
  REACT_APP_GA4_MEASUREMENT_ID = "G-BDZZKFKYDV"